# Generated by Django 2.2.4 on 2019-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('information', models.TextField()),
            ],
        ),
    ]
