# Generated by Django 2.2.4 on 2019-09-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('rdv_type', models.CharField(blank=True, choices=[('phone', 'phone'), ('sur_place', 'sur_place')], max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Token_rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Votre nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Votre email')),
                ('duration', models.CharField(choices=[('1', 'moins de 15min'), ('2', 'entre 15min et 30min'), ('3', 'plus que 30min')], default='1', max_length=2, verbose_name="durée de l'appel prévue")),
                ('commentaire', models.TextField()),
                ('rdv_shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log.RendezVous')),
            ],
        ),
    ]
