# Generated by Django 2.2.4 on 2019-09-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_rdv',
            name='rdv_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.RendezVous'),
        ),
    ]
