# Generated by Django 2.2.4 on 2019-09-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='name',
            field=models.CharField(default='phone', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rdv_type',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('sur_place', 'sur_place')], max_length=100),
        ),
    ]
