# Generated by Django 2.2.4 on 2019-09-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_token_rdv_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_rdv',
            name='company',
            field=models.CharField(max_length=254, verbose_name="Nom de l'entreprise"),
        ),
    ]
