# Generated by Django 2.2.4 on 2019-09-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_remove_rendezvous_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handeler_name', models.CharField(max_length=200)),
                ('handeler_email', models.EmailField(max_length=254)),
                ('input_text', models.TextField()),
            ],
        ),
    ]
