# Generated by Django 2.2.4 on 2019-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20190906_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='dispo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
