# Generated by Django 2.2.4 on 2019-09-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_rendezvous_dispo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='dispo',
            new_name='token',
        ),
    ]
